on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
name: CI
jobs:
  formatted:
    name: Formatted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cashapp/activate-hermit@v1
      - run: |
          just fmt
          git diff
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cashapp/activate-hermit@v1
      - name: Setup xattr-supported filesystem
        run: |
          dd if=/dev/zero of=/tmp/xattr.img bs=1M count=1024
          mkfs.ext4 /tmp/xattr.img
          mkdir -p /tmp/xattr-fs
          sudo mount -o loop,user_xattr /tmp/xattr.img /tmp/xattr-fs
          sudo chmod 1777 /tmp/xattr-fs
      - name: Run tests
        run: just test
        env:
          TMPDIR: /tmp/xattr-fs
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      GOPROXY: direct
    steps:
      - uses: actions/checkout@v4
      - uses: cashapp/activate-hermit@v1
      - run: just lint
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: ["test", "lint"]
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cashapp/activate-hermit@v1
      - run: goreleaser release --fail-fast
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
