on:
  push:
    branches:
      - main
  pull_request:
name: CI
jobs:
  formatted:
    name: Formatted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: cashapp/activate-hermit@v1
      - run: |
          just fmt
          git diff --exit-code
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: cashapp/activate-hermit@v1
      - name: Run tests
        run: just test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: cashapp/activate-hermit@v1
      - run: just lint
